services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    depends_on:
      - postgres
    ports:
      - 10051:10051    
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_SERVER_PORT: 5432
    volumes:
      - zabbix-server-data:/var/lib/zabbix
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
      - zabbix-export-data:/var/lib/zabbix/export
    restart: unless-stopped

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-fronted
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_SERVER_HOST: 0.0.0.0 # Change the IP
      PHP_TZ: ${PHP_TZ}
      ZBX_SERVER_PORT: 10051
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - zabbix-web-data:/usr/share/zabbix 

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_ACTIVE_ALLOW: true
      ZBX_HOSTNAME: zabbix-agent
      ZBX_SERVER_HOST: 0.0.0.0 # Change the IP
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAMEITEM: system.hostname
    ports:
      - 10050:10050        
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
    privileged: true

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432 
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgresql-data:
  zabbix-server-data:
  zabbix-snmptraps-data:
  zabbix-export-data:
  zabbix-web-data: