services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/storage/sonarr:/config
      - /mnt/Shows:/Shows
      - /mnt/Downloads:/downloads
    restart: unless-stopped