services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /mnt/storage/npm/data:/data
      - /mnt/storage/npm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped